### ISSUE TITLE
Zustimmung signalisieren

### ISSUE THREAD

**Issue by ChrisBtt** [smolkin75/fshelper#4]
Bei Redebeiträgen kann man seine Zustimmung nicht einfach durch eine Reaktion auf einen Satz im Chat signalisieren. In Präsenzsitzungen war das Hände wedeln dafür das Mittel der Wahl. 
Hier wäre vllt etwas wie fs!zs oder so etwas sinnvoll. Oder eine andere festgelegte Reaktion, die jeder erkennt.

**Comment by nick75g** [comment]
Der Command fs!zs wurde hinzugefügt, womit man seine Zustimmung signalisieren kann (entweder einfach so oder als Antwort auf eine Chatnachricht)
