### ISSUE TITLE
Dringlicher Redebeitrag

### ISSUE THREAD

**Issue by ChrisBtt** [smolkin75/fshelper#5]
In der Fachschaftssitzung kommt es bei längeren Diskussionen dazu, dass mehrere Gesprächsthemen sich überlappen und Meldungen sich zum Teil auf den vorletzten Beitrag oder so beziehen. Dazu wäre ein "Direkt dazu" wie es in Präsenz üblich war angebracht etwa fs!dm (direct message) in der der Redner an den Anfang statt das Ende der Redeliste kommt.

**Comment by nick75g** [comment]
Es wurden die commands fs!dd unf fs!ddzz hinzugefügt, um eine Meldung "Direkt Dazu" auszuführen bzw. diese zurückzuziehen. fs!dd-Meldungen werden vor fs!m-Meldungen abgearbeitet.
